In [1]:
import numpy as np

### Create Arrays from Python Lists

In [2]:
np.array([3,5,7,8])

array([3, 5, 7, 8])

### Create array with specifique data type

In [3]:
np.array([3,5,7,8],dtype='float32')

array([3., 5., 7., 8.], dtype=float32)

### Create multi-dimensionnal array using List of lists

In [4]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Create Arrays from scrash

In [6]:
#Create a lengh-10 integer array filled with 0
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#Create a 3*5 floating-point array filled with ones
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#Create a 3*5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
#Create am array filled with a linear sequence
#Strarting at 0, ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#Create a 3*3 Array of uniformely distributed random values between 0 and 1
np.random.random((3,3))

array([[0.79233812, 0.82526674, 0.54593252],
       [0.0621533 , 0.12693273, 0.0566786 ],
       [0.81672018, 0.92439816, 0.00478597]])

In [12]:
#Create a 3*3 Array of normaly distributed random values with mean 0 and std 1
np.random.normal(0,1,(3,3))

array([[-0.2926721 ,  1.90280944, -0.7650476 ],
       [-0.2444836 ,  0.35541083,  0.10737869],
       [-2.15843545, -0.21981578,  1.70052333]])

In [13]:
#Create a 3*3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[2, 5, 1],
       [5, 4, 9],
       [6, 3, 2]])

In [14]:
#Create a 3*3 identity matrix
np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Create ab uninitialized array of 3 integers
#The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

## Silicing Array

In [17]:
arr = np.array([1,2,35,56,90,7,99])
print(arr[1:5])

[ 2 35 56 90]


In [18]:
#Slice elemets from 4 to the end of the array
print(arr[4:])

[90  7 99]


In [19]:
#Slice elemets from 4(not included) to the end of the array
print(arr[:4])

[ 1  2 35 56]


## Negative Slicing

In [20]:
#Slice from the index 3 from the end to index 1 from the end
print(arr[-3:-1])

[90  7]


## use the step value to determine the step of slicing

In [24]:
#Return every other element from indec 1 to index 5
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [25]:
#Return every other element from the entire array
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

In [27]:
# From second element, slice elements from index 1 to index 4(not included)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [30]:
# From both elements, return index 2
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0:2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


In [31]:
#From both elements, slice index 1 to index 4(ont include), this will return a 3-D array
# From bot elements, return index 2
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


## Numpy Array Copy vs View

In [40]:
#Make a copy, change the original array, and display both arrays
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=45
print(arr)
print(x)

[45  2  3  4  5]
[1 2 3 4 5]


In [38]:
#Make a view, change the original array, and display boths arrays. 
#The view should affected by the change
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=45
print(arr)
print(x)

[45  2  3  4  5]
[45  2  3  4  5]


In [42]:
#Make a view, change the original array, and display boths arrays. 
#The view should affected by the change
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=45
print(arr)
print(x)

[45  2  3  4  5]
[45  2  3  4  5]


## Check if Array Owns its Data

In [43]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [45]:
#Print the shape of 2-D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [89]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4,5
#and verify that last dimension has value 4
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(f'Shape of the array is',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of the array is (1, 1, 1, 1, 4)


## Reshapping arrays

In [62]:
# Convert the following 1-D array wit 12 elements into a 2-D array.
# The outemost dimension will have 4 arrays, each with 3 elements
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
#Reshape from 1-D to 3-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(2,3,2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [63]:
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,4)
print(new_arr) 

[[1 2 3 4]
 [5 6 7 8]]


## Unknow Dimension

In [64]:
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,2,-1)
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flatteming the array

In [67]:
#Convert multi-dimensional array inton 1D array use reshape(-1) to do this
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
new_arr = arr.reshape(-1)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


## Numpy Array Joining

In [71]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.concatenate((arr1,arr2))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [72]:
#Join two 2-D arrays along rows(axis=1)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[57,6],[7,8]])
new_arr = np.concatenate((arr1,arr2),axis=1)
print(new_arr)

[[ 1  2 57  6]
 [ 3  4  7  8]]


## Joinning Arrays Using Stack Functions

In [73]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.stack((arr1,arr2),axis=1)
print(new_arr)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [74]:
#Stacking along Rows
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.hstack((arr1,arr2))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [75]:
#Stacking along Columns
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.vstack((arr1,arr2))
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [76]:
##Stacking along Height(depth)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.dstack((arr1,arr2))
print(new_arr)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


## Numpy Searchin Arrays

In [77]:
arr = np.array([1,3,4,6,7,4])
print(np.where(arr == 4))

(array([2, 5], dtype=int64),)


In [78]:
arr = np.array([ 1 , 2,  3,  4,  5,  6,  7,  8,  9, 10])
print(np.where(arr%2==0))

(array([1, 3, 5, 7, 9], dtype=int64),)


## Search Sorted

In [79]:
arr = np.array([ 1 , 2,  3,  4,  5,  6,  7,  8,  9, 10])
print(np.searchsorted(arr,7))

6


In [81]:
#Search from right side
arr = np.array([ 1 , 2,  3,  4,  5,  6,  7,  8,  9, 10])
print(np.searchsorted(arr,7,side='right'))

7


In [82]:
#Search multiple value
arr = np.array([ 1 , 2,  3,  4,  5,  6,  7,  8,  9, 10])
print(np.searchsorted(arr,[2,3,9]))

[1 2 8]


## Sort Arrays

In [84]:
arr = np.array([ 1 , 2,  3,  4,  5,  6,  7,  8,  9, 10,0])
print(np.sort(arr))

[ 0  1  2  3  4  5  6  7  8  9 10]


### We can sort a string array even 2-D array

## Numpy Filter Array

In [85]:
arr = np.array([ 1 , 2,  3,  4,  5,  6,  7,  8,  9, 10])
filter_arr = []
for elt in arr:
    if elt%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [87]:
#Create filtering directly from array
arr = np.array([ 1 , 2,  3,  43,  5,  6,  7,  8,  9, 10])
filter_arr = arr>42
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False False False  True False False False False False False]
[43]
